#! /usr/bin/env sh

assert_equal() {
  expected="$1"
  command="$2"
  printf "• $command "
  result=`$command`
  if [ "$result" == "$expected" ]; then
    printf "\033[7;32m OK \033[0m\n"
  else
    printf "\033[7;31m ERROR! \033[0m expected \033[4m$expected\033[0m but got \033[4m$result\033[0m\n"
    exit 1
  fi
}
