#! /usr/bin/env sh

# Display one or more strings with optional xterm escape sequences. Include "\n"
# where desired.
say() {
  for argument in "$@"; do
    printf "$argument"
  done
}

assert_equal() {
  expected=$1
  command=$2
  say "• $command "
  result=`$command`
  if [ "$result" == "$expected" ]; then
    say "\033[7;32m OK \033[0m\n"
  else
    say "\033[7;31m ERROR! \033[0m expected \033[4m$expected\033[0m but got \033[4m$result\033[0m\n"
    exit 1
  fi
}
