#!/usr/bin/env sh

source src/support/util.sh

PKG_DIR=pkg
PKG=$PKG_DIR/euthanize
BIN=bin/euthanize

perform Cleaning "rm -fr $PKG_DIR" "mkdir $PKG_DIR"

perform Building "
  for file in \$(find src -name *.sh); do
    if [ ! -f "$PKG" ]; then
      printf \"#!/usr/bin/env sh\\\n\" >"$PKG"
    fi
    printf \"\\\n\" >>"$PKG"
    printf \"#--------------------------------------------------------------------------------\\\n\" >>"$PKG"
    printf \"# \$file\\\n\" >>"$PKG"
    cat \"\$file\" >>"$PKG"
  done

  printf \"\\\n\" >>"$PKG"
  printf \"#--------------------------------------------------------------------------------\\\n\" >>"$PKG"
  printf \"main \\\"\\\$@\\\"\\\n\" >>"$PKG"
"

inquire 'Package up to date?' "
  if [ -s "$BIN" ] && [ -s "$PKG" ]; then
    diff "$PKG" "$BIN"
    return \$?
  fi

  return 1
"
if [ $? -ne 0 ]; then
  perform Packaging "
    chmod a+x "$PKG"
    cp "$PKG" "$BIN"
  "
fi
