#!/usr/bin/env sh

source src/support/util.sh

run_tests() {
  local file_count=0
  local assertion_count=0
  for file in $(find test -name *_test.sh); do
    local file_count=$(($file_count+1))
    say "________________________________________________________________________________"
    say "$file"

    # Run tests, which exit upon a failed assertion.
    source "$file" 2>&1

    # Run tests again to capture their output for computing statistics.
    local result=$($file 2>/dev/null)

    local lines=$(($(printf "$result\n" | wc -l)))
    local assertion_count=$(($assertion_count+$lines))
  done
  say "================================================================================"
  say "Approximately $assertion_count passing assertions in $file_count test files"
}
run_tests
