#!/usr/bin/env sh

build() {
  if [ $# -lt 2 ]; then
    printf "\033[31m$# for 2-n arguments passed to $0\033[0m\n" >&2
    exit 1
  fi

  local OUT="$1"
  shift

  printf "#!/usr/bin/env sh\n" >"$OUT"
  for file in "$@"; do
    printf "\n" >>"$OUT"
    printf "#--------------------------------------------------------------------------------\n" >>"$OUT"
    printf "# $file\n" >>"$OUT"
    cat "$file" >>"$OUT"
  done
  printf "\n" >>"$OUT"
  printf "#--------------------------------------------------------------------------------\n" >>"$OUT"
  printf "main \"\$@\"\n" >>"$OUT"
  chmod a+x "$OUT"
}
build "$@"
