#!/usr/bin/env sh

build() {
  if [ $# -lt 2 ]; then
    printf "\033[31m$# for 2-n arguments passed to $0\033[0m\n" >&2
    exit 1
  fi

  local BIN="$1"
  shift

  printf "#!/usr/bin/env sh\n" >"$BIN"
  for file in "$@"; do
    printf "\n" >>"$BIN"
    printf "#--------------------------------------------------------------------------------\n" >>"$BIN"
    printf "# $file\n" >>"$BIN"
    cat "$file" >>"$BIN"
  done
  printf "\n" >>"$BIN"
  printf "#--------------------------------------------------------------------------------\n" >>"$BIN"
  printf "main \"\$@\"\n" >>"$BIN"
  chmod a+x "$BIN"
}
build "$@"
