#!/usr/bin/env sh

run_tests() {
  if [ $# -lt 1 ]; then
    printf "\033[31m$# for 1-n arguments passed to $0\033[0m\n" >&2
    exit -1
  fi

  local started_at=$(($(date '+%s')))
  local file_count=0
  local assertion_count=0
  for file in "$@"; do
    local file_count=$(($file_count+1))

    # Run tests, which exit upon a failed assertion.
    "$file" >/dev/null

    # Run tests again to capture their output for computing statistics.
    local result=$("$file" 2>/dev/null)

    if [ "$result" == '' ]; then
      local lines=0
    else
      local lines=$(($(printf "$result\n" | wc -l)))
    fi
    local assertion_count=$(($assertion_count+$lines))
  done
  local duration=$(($(date '+%s')-$started_at))
  printf "* Approximately $assertion_count passing assertions\n"
  printf "* In $file_count test files\n"
  printf "* Completed $(date '+%a') "
  printf $(($(date '+%m')))
  printf $(date '+/%d')
  printf ' '
  printf $(date '+%l:%M:%S')
  printf ' '
  printf "$(date '+%p %Z')\n"
  printf "* In approximately $duration seconds\n"
}
run_tests "$@"
