#!/usr/bin/env sh

run_tests() {
  if [ $# -lt 1 ]; then
    printf "\033[31m$# for 1-n arguments passed to $0\033[0m\n" >&2
    exit 1
  fi

  local file_count=0
  local assertion_count=0
  for file in "$@"; do
    local file_count=$(($file_count+1))

    # Run tests, which exit upon a failed assertion.
    source "$file" >/dev/null

    # Run tests again to capture their output for computing statistics.
    local result=$($file 2>/dev/null)

    local lines=$(($(printf "$result\n" | wc -l)))
    local assertion_count=$(($assertion_count+$lines))
  done
  printf "Approximately $assertion_count passing assertions in $file_count test files\n"
}
run_tests "$@"
